### ISSUE TITLE
Maybe it can be more explicit?

### ISSUE THREAD

**Issue by sodaling** [bsm/ratelimit#3]
https://github.com/bsm/ratelimit/blob/8e32603e22a2014227edb38946de25e32b199faf/ratelimit.go#L69
Maybe this code means to set the allowance to max?

It can be:
```golang
atomic.StoreUint64(&t.allowance, max)
```

Just curious.

**Comment by dim** [comment]
Well, no, since `max` may change and you want to subtract the `current` (i.e. the already spent credits from it)

**Comment by sodaling** [comment]
No wonder！
Thx
