### ISSUE TITLE
missing version v1

### ISSUE THREAD

**Issue by ikottman** [bsm/ratelimit#7]
Hello! 

Recently it seems the v1 tag was deleted for this project. This breaks (admittedly deprecated) versions of the go-redis package: https://github.com/redis/go-redis/issues/2353

Is there any chance of putting v1 back up?

**Comment by dim** [comment]
Sorry, but there never was a v1 tag, it's just gopkg.in interpretation. You should really not use `gopkg.in/bsm/ratelimit.v1` anymore, it was never intended to be used

**Comment by ikottman** [comment]
Oof, that's unfortunate. I'll try updating to later go-redis versions which don't rely on that missing version. Thanks for the quick response!

**Comment by dim** [comment]
I added a `v1` branch which gopkg.in apparently supports. Please let me know if that helped.

**Comment by dim** [comment]
But yes, you should update to a later go-redis version, as the one is using is hopelessly out of date

**Comment by g3kk0** [comment]
I also just noticed this. Seems to be working now. Thanks for the quick fix!

**Comment by ikottman** [comment]
Yep that fixed our build! Thank you so much, this gives me more breathing room to test updating off that ancient version.
